name: UiPathRunTests
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: self-hosted
    steps:
      # Checkout code from this repo
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Print Working Directory
        run: |
          pwd
          ls
      # Run UiPath Test using UiPath CLI
      - name: Pack and Test
        run: |
          cd C:\UiPath.CLI.Windows.23.6.8581.19168\tools\
          uipcli.exe test run "https://cloud.uipath.com/" SalesEngineer -A cybertron -I 2d3dfd3f-701c-4842-85d8-4f0f937dcf42 -S LkfYSb3e*vzQ571E --applicationScope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Monitoring OR.Robots.Read OR.Settings.Read OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users.Read" -s "SAP Create Order in GUI" -o "Ajay Jagtap"
